services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:4000
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    env_file: ./server/.env
    environment:
      - FRONTEND_URL=http://localhost:3000
